### PR TITLE
Rename @iopipe/iopipe to just iopipe

### PR DESCRIPTION
**Pull request by kolanos**
Closes https://github.com/iopipe/iopipe-js-core/issues/213

### CODE REVIEW

**Comment by kolanos** [comment]
Pros:
* No need to update `iopipe` imports
* No need to uninstall/reinstall `iopipe`/`@iopipe/core`
* Easier to steer users to kitchen sink
* No need to update serverless plugin

Cons:
* Replaces one package with another, unexpected behavior for devs

**Comment by pselle** [comment]
:-1: Downvoting this PR per comments in Slack

**Comment by kolanos** [comment]
@ewindisch Thoughts?

**Comment by ewindisch** [comment]
I think if we wanted to publish under both names that could be an acceptable compromise? I am a 👎  on this patch as it exists currently and agree we'd need more discussion on the right solution.

**Comment by kolanos** [comment]
@ewindisch Going to close this as the thumbs down win it. We can discuss further in other channels.

**Pull request closed without merging**
