### PR TITLE
Upgrade @iopipe/core dependency

### PR DESCRIPTION
**Pull request by kolanos**

### CODE REVIEW

**Comment by kolanos** [comment]
@coreylight Seeing this error in CI even though `@iopipe/core` has been upgrade to `v1.13.0`:

```
mark.start(test-mark) was called from @iopipe/iopipe but this method was not available. You may have called this method outside of an invocation or @iopipe/core needs to be upgraded to satisfy version ^1.11.0
```

**Comment by coreylight** [comment]
@kolanos this needs more investigation as I currently believe that upgrading this dep will not solve the particular issue you noted. From what I have seen, that happens when there are two copies of `@iopipe/core` in the `node_modules` directory.

**Comment by kolanos** [comment]
@coreylight Is there something semver related I need to do to make this a release?comm

**Comment by coreylight** [comment]
If you wanted to make this a feature release you'd squash this PR into master with a commit message starting with:

```
feat(upgrade core): upgrade @iopipe/iopipe
```

Some documentation:
https://github.com/semantic-release/semantic-release#commit-message-format
https://gist.github.com/stephenparish/9941e89d80e2bc58a153

**Comment by pselle** [comment]
@kolanos You can also run `yarn commit` when committing to a repo released this way, since that's generally set up with a flow to help you commit in the appropriate way

**Pull request merged**
